Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "jenkisServer" do |jenkisServer|
    jenkisServer.vm.box = "ubuntu/bionic64"
    jenkisServer.vm.network "private_network", ip: "192.168.56.11"
    jenkisServer.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt update
  sudo apt install openjdk-11-jdk -y
  sudo apt install maven -y
  curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
  sudo apt-get update
  sudo apt-get install jenkins -y
  SHELL
end

